const storageKey = 'learn-guide-profile';
const savedProfile = JSON.parse(localStorage.getItem(storageKey) || '{}');
const state = {
  page: 'Home', query: '', selectedTech: 'Pega PRPC',
  bookmarks: savedProfile.bookmarks || JSON.parse(localStorage.getItem('learn-guide-bookmarks') || '[]'),
  completed: savedProfile.completed || [], quizIndex: 0, quizScore: 0,
  scenarioStep: 0, assessmentIndex: 0, assessmentAnswers: []
};

const technologies = [
  { name: 'Pega PRPC', short: 'P', className: 'pega', level: 'Intermediate', progress: 43, topic: 'Case lifecycle fundamentals', topics: ['Case lifecycle fundamentals', 'Data pages and sources', 'App Studio foundations', 'Security and access groups'] },
  { name: 'Azure Cloud', short: 'A', className: 'azure', level: 'Fundamental', progress: 25, topic: 'Identity and access management', topics: ['Cloud service models', 'Identity and access management', 'Virtual networking basics', 'Azure storage options'] },
  { name: 'DevOps', short: 'D', className: 'devops', level: 'Intermediate', progress: 37, topic: 'Continuous integration patterns', topics: ['Continuous integration patterns', 'Pipeline troubleshooting', 'Release strategies', 'Observability fundamentals'] }
];
const lessons = {
  'Case lifecycle fundamentals': { summary: 'Understand how work moves through a Pega case from intake to resolution.', body: 'A case lifecycle is a sequence of stages that guides work toward an outcome. Stages group related steps, make ownership visible, and create consistent handoffs.', source: 'Pega Academy: Case Management' },
  'Data pages and sources': { summary: 'Explore how Pega retrieves and reuses application data.', body: 'Data pages provide a reusable view of data. They separate data access from the UI and can source information from a connector, a report, or another data page.', source: 'Pega Platform documentation' },
  'Cloud service models': { summary: 'Compare infrastructure, platform, and software as a service.', body: 'IaaS gives you control over virtual infrastructure, PaaS manages the runtime platform, and SaaS delivers a complete application. The right model depends on how much operational responsibility your team wants.', source: 'Microsoft Learn: Cloud concepts' },
  'Identity and access management': { summary: 'Create a foundation for secure access to Azure resources.', body: 'Azure role-based access control assigns the minimum permissions needed for a task. Scope can be applied at management group, subscription, resource group, or resource level.', source: 'Microsoft Learn: Azure RBAC' },
  'Continuous integration patterns': { summary: 'Make integration frequent, visible, and repeatable.', body: 'Continuous integration validates small changes quickly through automated builds and tests. Fast feedback reduces integration risk and gives teams a dependable signal before release.', source: 'Microsoft Learn: DevOps fundamentals' },
  'Pipeline troubleshooting': { summary: 'Use a consistent path to isolate failed delivery stages.', body: 'Start with the first failing task, inspect its logs, verify inputs and permissions, then reproduce the smallest failing step. Treat the pipeline as a system of observable stages.', source: 'Microsoft Learn: Troubleshoot pipelines' }
};
const quiz = [
  { question: 'Which Azure service controls access using roles and scopes?', options: ['Azure RBAC', 'Azure DNS', 'Azure Monitor', 'Azure Storage'], answer: 0, explanation: 'Azure role-based access control uses roles assigned at a defined scope.' },
  { question: 'What is the first useful signal when a CI pipeline fails?', options: ['The last deployment date', 'The first failing task and its logs', 'The team roster', 'The repository size'], answer: 1, explanation: 'The first failing task usually identifies the earliest broken assumption.' },
  { question: 'What does a Pega case stage group?', options: ['Related work and steps', 'Cloud subscriptions', 'Source repositories', 'User passwords'], answer: 0, explanation: 'Stages group related steps and make ownership and progress visible.' }
];
const scenario = [
  { title: 'A release is blocked', text: 'A deployment pipeline fails after the build succeeds. The team says it worked yesterday. What do you inspect first?', options: ['Delete the pipeline', 'Open the first failed task logs', 'Change every secret', 'Skip the deployment checks'], answer: 1, feedback: 'Good choice. Start at the first failed task and use its logs to narrow the cause.' },
  { title: 'The task still fails', text: 'The logs show an authorization error while publishing an artifact. What is the next focused check?', options: ['Verify the service connection scope', 'Rewrite the application', 'Increase the UI timeout', 'Remove the artifact'], answer: 0, feedback: 'Correct. Confirm the identity has the required permission at the target scope.' },
  { title: 'The fix is ready', text: 'The service connection has the right permission. What closes the loop?', options: ['Rerun the smallest failed stage', 'Wait for another day', 'Disable the check', 'Create a second repository'], answer: 0, feedback: 'Exactly. Re-run the smallest failed stage, then record the resolution.' }
];
const assessment = [
  { question: 'You need a complete managed application delivered to users. Which model best fits?', options: ['IaaS', 'PaaS', 'SaaS'], answer: 2 },
  { question: 'A Pega stage is most useful for organizing...', options: ['Related case work', 'Cloud billing', 'Git branches'], answer: 0 },
  { question: 'A healthy CI practice favors...', options: ['Large infrequent merges', 'Small changes with automated validation', 'Manual release notes only'], answer: 1 }
];

function icon(symbol) { return `<span class="icon">${symbol}</span>`; }
function navItem(label, glyph) { return `<button class="nav-item ${state.page === label ? 'active' : ''}" data-page="${label}">${icon(glyph)}<span>${label}</span></button>`; }
function button(label, action, className = 'ghost-button') { return `<button class="${className}" data-action="${action}">${label}</button>`; }
function saveProfile() { localStorage.setItem(storageKey, JSON.stringify({ bookmarks: state.bookmarks, completed: state.completed })); }
function progressFor(tech) { const done = tech.topics.filter(topic => state.completed.includes(topic)).length; return Math.max(tech.progress, Math.round((done / tech.topics.length) * 100)); }
function bookmarkButton(id) { const saved = state.bookmarks.includes(id); return `<button class="bookmark ${saved ? 'saved' : ''}" data-bookmark="${id}" title="${saved ? 'Remove bookmark' : 'Bookmark topic'}">${saved ? '★' : '☆'}</button>`; }
function pageIntro(eyebrow, title, text) { return `<div class="eyebrow">${eyebrow}</div><h1>${title}</h1><p class="intro">${text}</p>`; }

function render() {
  document.querySelector('#app').innerHTML = `<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">L</div><div class="brand-copy"><div class="brand-name">Learn & Guide</div><span class="brand-sub">SkillPilot workspace</span></div></div><nav><div class="nav-group"><div class="nav-label">Workspace</div>${navItem('Home', '⌂')} ${navItem('My Progress', '◔')} ${navItem('Bookmarks', '☆')}</div><div class="nav-group"><div class="nav-label">Technology</div>${navItem('Pega PRPC', 'P')} ${navItem('Azure Cloud', 'A')} ${navItem('DevOps', 'D')}</div><div class="nav-group"><div class="nav-label">Learning</div>${navItem('Learn', '▤')} ${navItem('Explore / Q&A', '⌕')} ${navItem('Practice', '✓')} ${navItem('Scenario Lab', '◈')} ${navItem('Assessment', '▥')}</div></nav><div class="sidebar-bottom"><div class="eyebrow">Your profile</div><p>Saved locally and ready to sync with your OneDrive folder.</p>${button('Export profile', 'export-profile')}</div></aside><main class="main"><header class="topbar"><div class="search">⌕<input id="global-search" placeholder="Search topics, questions, sources" value="${state.query}" /><kbd>⌘ K</kbd></div><div class="top-actions"><div class="status"><span class="status-dot"></span> Profile saved</div><button class="top-icon" data-action="theme" title="Toggle theme">☼</button><div class="avatar">JD</div></div></header><section class="content">${renderPage()}</section></main></div><div class="overlay" id="command-overlay"><div class="command"><input id="command-input" placeholder="Jump to a topic or workspace area..." /><div class="command-list">${commandItem('⌂', 'Go to dashboard', 'See your progress and recommendations', 'Home')}${commandItem('✓', 'Practice a skill', 'Try a quiz or troubleshooting exercise', 'Practice')}${commandItem('◈', 'Open scenario lab', 'Work through a realistic technical scenario', 'Scenario Lab')}${commandItem('▥', 'Take an assessment', 'Check your current learning level', 'Assessment')}</div></div></div><div class="toast" id="toast"></div>`;
  bindEvents();
}
function commandItem(glyph, title, sub, page) { return `<button class="command-item" data-page="${page}">${icon(glyph)}<span><strong>${title}</strong><small>${sub}</small></span></button>`; }
function renderPage() {
  if (state.page === 'Home') return renderHome();
  if (state.page === 'Learn' || technologies.some(t => t.name === state.page)) return renderLearn(state.page === 'Learn' ? state.selectedTech : state.page);
  if (state.page === 'Explore / Q&A') return renderExplore();
  if (state.page === 'Practice') return renderPractice();
  if (state.page === 'Scenario Lab') return renderScenario();
  if (state.page === 'Assessment') return renderAssessment();
  if (state.page === 'My Progress') return renderProgress();
  return renderBookmarks();
}
function renderHome() { return `${pageIntro('Thursday, 17 September 2026', 'Continue building your<br />technology skills.', 'A focused path through Pega PRPC, Azure Cloud, and DevOps, shaped around how you learn.')}<div class="hero-grid"><article class="hero-card"><div class="eyebrow">Your learning journey</div><h2>Small steps compound into confident practice.</h2><p>Keep your momentum going. You are making steady progress across all three technology paths.</p><div class="progress-row"><div class="progress-track"><div class="progress-fill" style="width: 34%"></div></div><span class="progress-value">34% overall</span></div></article><article class="resume-card"><div class="resume-top"><span class="tech-pill">Pega PRPC</span>${bookmarkButton('Case lifecycle fundamentals')}</div><h3>Case lifecycle fundamentals</h3><p>Understand how work moves through a Pega case from intake to resolution.</p><div class="resume-meta"><span>Intermediate · 12 min</span><strong>${state.completed.includes('Case lifecycle fundamentals') ? 'Complete' : '43%'}</strong></div><div class="line" style="margin-top: 11px"><i style="width: ${state.completed.includes('Case lifecycle fundamentals') ? '100' : '43'}%; background: var(--cyan)"></i></div>${button('Continue learning →', 'open-lesson:Case lifecycle fundamentals', 'open-action')}</article></div><div class="section-head"><h2>Technology paths</h2>${button('View learning map →', 'page:Learn', 'section-link')}</div><div class="tech-grid">${technologies.map(renderTechCard).join('')}</div>${renderHomeLower()}`; }
function renderTechCard(tech) { const progress = progressFor(tech); return `<article class="tech-card"><div class="tech-title"><div class="tech-logo ${tech.className}">${tech.short}</div><div><h3>${tech.name}</h3><small>${tech.level} path</small></div></div><div class="tech-stats"><div><strong>${progress}%</strong><span>overall progress</span></div><div style="text-align:right"><strong>${tech.topics.filter(t => state.completed.includes(t)).length}</strong><span>topics completed</span></div></div><div class="line"><i style="width:${progress}%; background:${tech.className === 'pega' ? 'var(--cyan)' : tech.className === 'azure' ? 'var(--blue)' : 'var(--purple)'}"></i></div><div class="card-footer"><span>Next: ${tech.topic}</span>${button('Open path →', `tech:${tech.name}`, 'open-action')}</div></article>`; }
function renderHomeLower() { return `<div class="lower-grid"><div><div class="section-head"><h2>Recommended for you</h2>${button('Explore all →', 'page:Explore / Q&A', 'section-link')}</div><div class="panel"><div class="recommendation"><div class="rec-icon blue">↗</div><div><h3>Azure identity and access</h3><p>Builds on your recent work with cloud foundations.</p></div>${bookmarkButton('Identity and access management')}</div><div class="recommendation"><div class="rec-icon orange">◇</div><div><h3>Pipeline troubleshooting</h3><p>Practice suggested from your latest assessment.</p></div>${bookmarkButton('Pipeline troubleshooting')}</div></div></div><div><div class="section-head"><h2>Quick actions</h2></div><div class="panel quick-actions">${button('Practice a skill', 'page:Practice', 'quick-action')} ${button('Scenario lab', 'page:Scenario Lab', 'quick-action')} ${button('Assessment', 'page:Assessment', 'quick-action')}</div></div></div>`; }
function renderLearn(techName) { const tech = technologies.find(t => t.name === techName) || technologies[0]; state.selectedTech = tech.name; return `${pageIntro(`${tech.name} · ${tech.level}`, 'Build your learning path.', 'Move from core concepts to practical application with short, focused lessons.')}<div class="path-header"><div class="tech-logo ${tech.className}">${tech.short}</div><div><h2>${tech.name}</h2><p>${tech.topics.length} topics in this path · ${progressFor(tech)}% progress</p></div><div class="path-switcher">${technologies.map(t => button(t.name, `tech:${t.name}`, t.name === tech.name ? 'mini-tab active' : 'mini-tab')).join('')}</div></div><div class="learning-map">${tech.topics.map((topic, index) => { const done = state.completed.includes(topic); return `<article class="lesson-card ${done ? 'done' : ''}"><div class="lesson-number">${done ? '✓' : String(index + 1).padStart(2, '0')}</div><div><div class="eyebrow">${index < 1 ? 'Start here' : index === 1 ? 'Build context' : 'Apply it'}</div><h3>${topic}</h3><p>${lessons[topic]?.summary || 'A guided lesson with examples, practical checks, and an official source.'}</p><div class="lesson-meta"><span>${index % 2 ? '8 min' : '12 min'} · ${done ? 'Completed' : 'Not started'}</span>${button(done ? 'Review lesson' : 'Start lesson', `open-lesson:${topic}`, 'open-action')}</div></div></article>`; }).join('')}</div>`; }
function renderExplore() { const filtered = Object.keys(lessons).filter(topic => `${topic} ${lessons[topic].summary}`.toLowerCase().includes(state.query.toLowerCase())); return `${pageIntro('Explore / Q&A', 'Find the next useful answer.', 'Search across concepts, explanations, and official learning sources.')}<div class="explore-toolbar"><input id="explore-search" placeholder="Search concepts or questions" value="${state.query}" /><span>${filtered.length} result${filtered.length === 1 ? '' : 's'}</span></div><div class="qa-grid">${filtered.map(topic => `<article class="qa-card"><div class="qa-card-top"><span class="tech-pill">${topic.includes('Azure') || topic.includes('Identity') || topic.includes('Cloud') ? 'Azure Cloud' : topic.includes('Pega') || topic.includes('Case') || topic.includes('Data') ? 'Pega PRPC' : 'DevOps'}</span>${bookmarkButton(topic)}</div><h3>${topic}</h3><p>${lessons[topic].summary}</p><div class="source-line">Official source · ${lessons[topic].source}</div>${button('Read explanation →', `open-lesson:${topic}`, 'open-action')}</article>`).join('')}</div>`; }
function renderPractice() { const item = quiz[state.quizIndex]; const finished = state.quizIndex >= quiz.length; return `${pageIntro('Practice', 'Turn knowledge into recall.', 'Short checks help you notice what is clear and where another example would help.')}<div class="practice-layout"><div class="panel quiz-panel">${finished ? `<div class="result-icon">✓</div><div class="eyebrow">Practice complete</div><h2>${state.quizScore} / ${quiz.length} correct</h2><p class="intro">${state.quizScore === quiz.length ? 'Excellent recall across this practice set.' : 'Review the explanations and try another focused session.'}</p>${button('Try again', 'reset-quiz', 'primary-button')}` : `<div class="quiz-progress">Question ${state.quizIndex + 1} of ${quiz.length}<span>${Math.round((state.quizIndex / quiz.length) * 100)}%</span></div><h2>${item.question}</h2><div class="option-list">${item.options.map((option, index) => `<button class="option" data-answer="${index}">${option}</button>`).join('')}</div><p class="hint">Choose the answer that best fits the principle, then review the explanation.</p>`}</div><aside class="panel practice-aside"><div class="eyebrow">Suggested focus</div><h3>Pipeline troubleshooting</h3><p>Use a repeatable diagnosis path: first failure, logs, permissions, smallest reproduction.</p>${button('Open scenario lab', 'page:Scenario Lab', 'ghost-button')}</aside></div>`; }
function renderScenario() { const item = scenario[state.scenarioStep]; const finished = state.scenarioStep >= scenario.length; return `${pageIntro('Scenario Lab', 'Practice the decision, not just the definition.', 'Work through a realistic delivery incident and see how each choice changes the investigation.')}<div class="scenario-layout"><div class="scenario-card"><div class="scenario-label">Incident ${Math.min(state.scenarioStep + 1, scenario.length)} of ${scenario.length}</div>${finished ? `<div class="result-icon">✓</div><h2>Investigation complete</h2><p>You followed the incident from failure signal to focused validation.</p>${button('Run scenario again', 'reset-scenario', 'primary-button')}` : `<h2>${item.title}</h2><p class="scenario-text">${item.text}</p><div class="option-list">${item.options.map((option, index) => `<button class="option" data-scenario-answer="${index}">${option}</button>`).join('')}</div>`}</div><aside class="panel scenario-aside"><div class="eyebrow">Investigation principle</div><h3>Reduce the search space</h3><p>Start with the earliest observable failure, then test one focused hypothesis at a time.</p></aside></div>`; }
function renderAssessment() { const item = assessment[state.assessmentIndex]; const finished = state.assessmentIndex >= assessment.length; return `${pageIntro('Assessment Center', 'Check your current learning level.', 'This is a learning signal, not a professional judgment. Use it to choose your next useful level of practice.')}<div class="assessment-card panel">${finished ? `<div class="result-icon">${state.assessmentAnswers.filter(Boolean).length}</div><div class="eyebrow">Recommended learning level</div><h2>${state.assessmentAnswers.filter(Boolean).length >= 2 ? 'Intermediate' : 'Fundamental'}</h2><p class="intro">Suggested next learning: ${state.assessmentAnswers.filter(Boolean).length >= 2 ? 'practice troubleshooting and design decisions.' : 'strengthen the core concepts with guided examples.'}</p>${button('Retake assessment', 'reset-assessment', 'primary-button')}` : `<div class="quiz-progress">Question ${state.assessmentIndex + 1} of ${assessment.length}<span>Initial knowledge check</span></div><h2>${item.question}</h2><div class="option-list">${item.options.map((option, index) => `<button class="option" data-assessment-answer="${index}">${option}</button>`).join('')}</div>`}</div>`; }
function renderProgress() { const completed = state.completed.length; return `${pageIntro('My Progress', 'Your learning, in view.', 'Track completed topics, revisit saved concepts, and choose the next focused action.')}<div class="stats-grid"><div class="stat-card"><strong>${completed}</strong><span>topics completed</span></div><div class="stat-card"><strong>${state.bookmarks.length}</strong><span>bookmarked topics</span></div><div class="stat-card"><strong>34%</strong><span>overall journey</span></div></div><div class="panel progress-panel"><div class="section-head"><h2>Path progress</h2>${button('Export profile', 'export-profile', 'section-link')}</div>${technologies.map(t => `<div class="progress-item"><div><strong>${t.name}</strong><span>${t.level} path · ${t.topics.filter(topic => state.completed.includes(topic)).length} lessons completed</span></div><div class="progress-bar"><i style="width:${progressFor(t)}%"></i></div><b>${progressFor(t)}%</b></div>`).join('')}</div>`; }
function renderBookmarks() { const saved = Object.keys(lessons).filter(topic => state.bookmarks.includes(topic)); return `${pageIntro('Bookmarks', 'Keep useful answers close.', 'Your saved topics stay in this browser profile so you can return to them later.')}<div class="qa-grid">${saved.length ? saved.map(topic => `<article class="qa-card"><div class="qa-card-top"><span class="tech-pill">Saved topic</span>${bookmarkButton(topic)}</div><h3>${topic}</h3><p>${lessons[topic].summary}</p>${button('Open topic →', `open-lesson:${topic}`, 'open-action')}</article>`).join('') : `<div class="panel empty-state"><div class="result-icon">☆</div><h2>No bookmarks yet</h2><p class="intro">Save a lesson or answer from Explore to build your personal reference shelf.</p>${button('Explore topics', 'page:Explore / Q&A', 'primary-button')}</div>`}</div>`; }

function openLesson(topic) { const lesson = lessons[topic] || { summary: 'Guided lesson', body: 'This lesson is part of your selected learning path.', source: 'Official learning source' }; document.querySelector('#command-overlay').classList.add('open'); document.querySelector('.command').innerHTML = `<div class="lesson-modal"><div class="eyebrow">Focused lesson</div><h2>${topic}</h2><p class="intro">${lesson.summary}</p><p>${lesson.body}</p><div class="source-line">${lesson.source}</div><div class="modal-actions">${button('Mark complete', `complete:${topic}`, 'primary-button')}${button('Close', 'close-command', 'ghost-button')}</div></div>`; bindEvents(); }
function bindEvents() {
  document.querySelectorAll('[data-page]').forEach(el => el.addEventListener('click', () => { state.page = el.dataset.page; closeCommand(); render(); }));
  document.querySelectorAll('[data-bookmark]').forEach(el => el.addEventListener('click', () => toggleBookmark(el.dataset.bookmark)));
  document.querySelectorAll('[data-action]').forEach(el => el.addEventListener('click', () => handleAction(el.dataset.action)));
  document.querySelectorAll('[data-answer]').forEach(el => el.addEventListener('click', () => answerQuiz(Number(el.dataset.answer))));
  document.querySelectorAll('[data-scenario-answer]').forEach(el => el.addEventListener('click', () => answerScenario(Number(el.dataset.scenarioAnswer))));
  document.querySelectorAll('[data-assessment-answer]').forEach(el => el.addEventListener('click', () => answerAssessment(Number(el.dataset.assessmentAnswer))));
  const search = document.querySelector('#global-search'); if (search) { search.addEventListener('input', e => { state.query = e.target.value; if (state.page === 'Explore / Q&A') render(); }); search.addEventListener('focus', openCommand); }
  const explore = document.querySelector('#explore-search'); if (explore) explore.addEventListener('input', e => { state.query = e.target.value; render(); });
  const commandInput = document.querySelector('#command-input'); if (commandInput) commandInput.addEventListener('input', e => { const term = e.target.value.toLowerCase(); document.querySelectorAll('.command-item').forEach(item => item.style.display = item.textContent.toLowerCase().includes(term) ? 'flex' : 'none'); });
  document.querySelectorAll('.command-item').forEach(item => item.addEventListener('click', () => { state.page = item.dataset.page; closeCommand(); render(); }));
}
function handleAction(action) { if (action === 'theme') { document.body.classList.toggle('dark'); showToast('Theme preference updated'); return; } if (action === 'export-profile') { const blob = new Blob([JSON.stringify({ bookmarks: state.bookmarks, completed: state.completed }, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'learn-guide-profile.json'; link.click(); showToast('Profile exported'); return; } if (action === 'close-command') { closeCommand(); return; } if (action === 'reset-quiz') { state.quizIndex = 0; state.quizScore = 0; render(); return; } if (action === 'reset-scenario') { state.scenarioStep = 0; render(); return; } if (action === 'reset-assessment') { state.assessmentIndex = 0; state.assessmentAnswers = []; render(); return; } if (action.startsWith('page:')) { state.page = action.slice(5); closeCommand(); render(); return; } if (action.startsWith('tech:')) { state.selectedTech = action.slice(5); state.page = state.selectedTech; render(); return; } if (action.startsWith('open-lesson:')) { openLesson(action.slice(13)); return; } if (action.startsWith('complete:')) { const topic = action.slice(9); if (!state.completed.includes(topic)) state.completed.push(topic); saveProfile(); closeCommand(); showToast('Lesson marked complete'); render(); } }
function toggleBookmark(id) { state.bookmarks = state.bookmarks.includes(id) ? state.bookmarks.filter(item => item !== id) : [...state.bookmarks, id]; saveProfile(); showToast(state.bookmarks.includes(id) ? 'Saved to your bookmarks' : 'Removed from bookmarks'); render(); }
function answerQuiz(index) { if (index === quiz[state.quizIndex].answer) state.quizScore += 1; state.quizIndex += 1; render(); }
function answerScenario(index) { const item = scenario[state.scenarioStep]; showToast(index === item.answer ? item.feedback : `Try again: ${item.feedback}`); if (index === item.answer) { state.scenarioStep += 1; render(); } }
function answerAssessment(index) { state.assessmentAnswers.push(index === assessment[state.assessmentIndex].answer); state.assessmentIndex += 1; render(); }
function openCommand() { const overlay = document.querySelector('#command-overlay'); if (overlay) overlay.classList.add('open'); const input = document.querySelector('#command-input'); if (input) input.focus(); }
function closeCommand() { const overlay = document.querySelector('#command-overlay'); if (overlay) overlay.classList.remove('open'); }
function showToast(message) { const toast = document.querySelector('#toast'); if (!toast) return; toast.textContent = message; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2200); }
document.addEventListener('keydown', e => { if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'k') { e.preventDefault(); openCommand(); } if (e.key === 'Escape') closeCommand(); });
render();
